name: Python Compile Check

on:
  push:
    branches:
      - "**"

  pull_request:
    branches:
      - "**"


jobs:

  compile:

    name: Compile Python Files

    runs-on: ubuntu-latest


    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"


      - name: Compile all Python files
        run: |
          python -m compileall src


      - name: Check examples
        run: |
          python -m compileall examples
